version: '3.7'

services:
  api:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ./data:/app/data
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SECRET=verysecret
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=api

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api
